name = "Aligator"
uuid = "5ed869e0-1a60-11e9-29ae-17f02fe22408"
version = "0.1.0"

[deps]
AlgebraicDependencies = "df504336-4c6f-11e9-304d-b3facd222262"
ContinuedFractions = "b28563ba-f3de-538b-bd45-5b40df25bcd0"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
Singular = "bcd08a7b-43d2-5ff7-b6d4-c458787f915c"
SymPy = "24249f21-da20-56a4-8eb1-6a02cf4ae2e6"
